// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Ly9uQbEaxvrbEnLul7l4bzfyAFe1c1c',
    appId: '1:14405538602:web:ba5420a2b4d72c7beec453',
    messagingSenderId: '14405538602',
    projectId: 'lmsystem-e68f6',
    authDomain: 'lmsystem-e68f6.firebaseapp.com',
    storageBucket: 'lmsystem-e68f6.appspot.com',
    measurementId: 'G-FT505J5G78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvQGz1lvC12o9Ky9EjQbkaxi0wGQjpl6w',
    appId: '1:14405538602:android:fd1aa3f9f5dc176beec453',
    messagingSenderId: '14405538602',
    projectId: 'lmsystem-e68f6',
    storageBucket: 'lmsystem-e68f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi2sxMA7a9JNFCSodEjGh52q9hSpDvwJQ',
    appId: '1:14405538602:ios:996ad8d1a254f74deec453',
    messagingSenderId: '14405538602',
    projectId: 'lmsystem-e68f6',
    storageBucket: 'lmsystem-e68f6.appspot.com',
    iosClientId: '14405538602-nepgao2uep0dah3ncf5sqk7male1a9u6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dummy1',
  );
}
